import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import Providers from "./providers";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});
export const metadata: Metadata = {
  title: "Kab-City Civil Registrar System",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/CCRO.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {" "}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
